import { Product } from './types';

export const CATEGORIES = [
  {
    id: 'rings',
    name: 'Rings',
    slug: 'rings',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600&auto=format&fit=crop',
    itemCount: 42,
    description: 'Stackable bands, solitaire sparklers & everyday elegance',
  },
  {
    id: 'earrings',
    name: 'Earrings',
    slug: 'earrings',
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=600&auto=format&fit=crop',
    itemCount: 56,
    description: 'Dainty studs, hoops, chandeliers & drops',
  },
  {
    id: 'necklaces',
    name: 'Necklaces',
    slug: 'necklaces',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600&auto=format&fit=crop',
    itemCount: 38,
    description: 'Chokers, pendant necklaces & layering chains',
  },
  {
    id: 'bracelets',
    name: 'Bracelets',
    slug: 'bracelets',
    image: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=600&auto=format&fit=crop',
    itemCount: 29,
    description: 'Tennis bracelets, cuff bangles & charm chains',
  },
  {
    id: 'mens',
    name: "Men's",
    slug: 'mens',
    image: 'https://images.unsplash.com/photo-1534126511673-b6899657816a?q=80&w=600&auto=format&fit=crop',
    itemCount: 18,
    description: 'Sleek silver chains, signet rings & minimalist cuffs',
  },
  {
    id: 'silver-925',
    name: 'Silver 925',
    slug: 'silver-925',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=600&auto=format&fit=crop',
    itemCount: 64,
    description: 'Certified 92.5% pure silver with anti-tarnish e-coating',
  },
  {
    id: 'gifts',
    name: 'Gifts',
    slug: 'gifts',
    image: 'https://images.unsplash.com/photo-1513094735237-8f2714d57c13?q=80&w=600&auto=format&fit=crop',
    itemCount: 35,
    description: 'Curated gift hampers, romantic sets & birthday specials',
  },
];

export const HERO_SLIDES = [
  {
    id: '1',
    title: 'Everyday Fine Jewelry',
    subtitle: 'Crafted for daily radiance. 925 Pure Silver & 18K Gold Plated.',
    tag: 'NEW FESTIVE LAUNCH',
    ctaText: 'Explore Collection',
    ctaLink: '/shop?category=Rings',
    bgImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1600&auto=format&fit=crop',
    colorTheme: 'light',
  },
  {
    id: '2',
    title: 'The Solitaire Symphony',
    subtitle: 'Lab-grown brilliance meeting master craftsmanship.',
    tag: 'BESTSELLERS 2026',
    ctaText: 'Shop Solitaires',
    ctaLink: '/shop?metal=Lab-grown+Diamonds',
    bgImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1600&auto=format&fit=crop',
    colorTheme: 'light',
  },
  {
    id: '3',
    title: 'Bespoke Personalization',
    subtitle: 'Complimentary custom engraving & velvet gift box packaging.',
    tag: 'GIFTING SUITE',
    ctaText: 'Personalize Now',
    ctaLink: '/shop?category=Gifts',
    bgImage: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=1600&auto=format&fit=crop',
    colorTheme: 'light',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'nihi-101',
    name: 'Aethel Solitaire Sparkle Ring',
    slug: 'aethel-solitaire-sparkle-ring',
    subtitle: 'Classic 4-prong setting with brilliant round cut AAA+ Zircon',
    category: 'Rings',
    metal: '925 Sterling Silver',
    rating: 4.9,
    reviewCount: 342,
    badge: 'Bestseller',
    description: 'Indulge in timeless romance with the Aethel Solitaire Ring. Cast in hallmarked 925 sterling silver with a thick protective rhodium coating to resist tarnishing, this centerpiece ring is adorned with a hand-selected 1.5-carat equivalent AAA+ Swiss Zircon cut to optimal refractive symmetry.',
    details: [
      'Pure 925 Sterling Silver base with thick Rhodium/Gold e-coating',
      'AAA+ Swiss Cut Heart & Arrows cubic zirconia center stone',
      'Hypoallergenic, Nickel-free & Lead-free (safe for sensitive skin)',
      'Includes Nihi Certificate of Authenticity & Velvet Ring Box',
      'Comfort-fit tapered inner band for seamless daily wear',
    ],
    dimensions: 'Center stone: 6.5mm (1.5 Ct Eq), Band width: 1.8mm',
    weightGrams: 2.85,
    warranty: '6-Month Anti-Tarnish & Plating Warranty',
    hallmark: 'BIS Hallmarked & 925 Pure Silver Stamp',
    allowsEngraving: true,
    engravingMaxChars: 12,
    hasSizes: true,
    sizeType: 'ring',
    availableSizes: ['US 5 (15.7mm)', 'US 6 (16.5mm)', 'US 7 (17.3mm)', 'US 8 (18.1mm)', 'US 9 (18.9mm)', 'US 10 (19.8mm)'],
    featuredImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop',
    variants: [
      {
        id: 'var-101-silver',
        name: 'Silver',
        colorHex: '#D8D8D8',
        priceINR: 2499,
        originalPriceINR: 3999,
        priceUSD: 32,
        originalPriceUSD: 52,
        sku: 'NIHI-RNG-SLV-01',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        id: 'var-101-rose-gold',
        name: 'Rose Gold',
        colorHex: '#E9708A',
        priceINR: 2699,
        originalPriceINR: 4299,
        priceUSD: 35,
        originalPriceUSD: 55,
        sku: 'NIHI-RNG-RG-01',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        id: 'var-101-yellow-gold',
        name: 'Yellow Gold',
        colorHex: '#D4AF37',
        priceINR: 2699,
        originalPriceINR: 4299,
        priceUSD: 35,
        originalPriceUSD: 55,
        sku: 'NIHI-RNG-YG-01',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    priceBreakdown: {
      metalType: '92.5% Sterling Silver (2.85g)',
      metalWeightGrams: 2.85,
      metalRatePerGramINR: 320,
      metalCostINR: 912,
      gemstoneDescription: 'AAA+ Swiss Solitaire Zircon (1.5ct eq)',
      gemstoneCostINR: 850,
      makingChargesINR: 520,
      gstINR: 217,
      totalINR: 2499,
    },
    reviews: [
      {
        id: 'rev-1',
        author: 'Ananya Sharma',
        rating: 5,
        date: '14 Feb 2026',
        title: 'Breathtaking clarity and shine!',
        comment: 'Received this in the rose gold finish as a Valentine gift. The packaging is top notch and the sparkle looks identical to real diamonds. Fits true to size!',
        verified: true,
        productVariant: 'Rose Gold / US 7',
      },
      {
        id: 'rev-2',
        author: 'Priya Iyer',
        rating: 5,
        date: '28 Jan 2026',
        title: 'Compliments non-stop at office',
        comment: 'I wear this everyday. The anti-tarnish coating is legit, zero discoloration after 2 months of handwashing.',
        verified: true,
        productVariant: 'Silver / US 6',
      },
    ],
  },
  {
    id: 'nihi-102',
    name: 'Luminary Floating Heart Pendant',
    slug: 'luminary-floating-heart-pendant',
    subtitle: 'Delicate open heart necklace set with micro-pave crystals',
    category: 'Necklaces',
    metal: '18K Gold Plated',
    rating: 4.8,
    reviewCount: 218,
    badge: 'Trending',
    description: 'An iconic tribute to modern romance. Suspended on a luminous 16-inch + 2-inch extender chain, the Luminary Floating Heart catches light from every angle with hand-set micro zircons on genuine 18K yellow or rose gold vermeil.',
    details: [
      '18K Gold Vermeil over 925 Sterling Silver base',
      'Micro-pavé stone setting by master artisans',
      'Adjustable 16" to 18" cable chain with lobster clasp and Nihi charm tag',
      'Water & sweat resistant coating',
      'Comes with Authenticity Card & Travel Pouch',
    ],
    dimensions: 'Heart motif: 14mm x 12mm, Chain: 40cm + 5cm extension',
    weightGrams: 3.4,
    warranty: '6-Month Plating & Authenticity Warranty',
    hallmark: '925 Hallmarked & 18K Vermeil Certified',
    allowsEngraving: true,
    engravingMaxChars: 8,
    hasSizes: false,
    featuredImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop',
    variants: [
      {
        id: 'var-102-rose-gold',
        name: 'Rose Gold',
        colorHex: '#E9708A',
        priceINR: 2899,
        originalPriceINR: 4499,
        priceUSD: 36,
        originalPriceUSD: 58,
        sku: 'NIHI-NCK-RG-02',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        id: 'var-102-silver',
        name: 'Silver',
        colorHex: '#D8D8D8',
        priceINR: 2699,
        originalPriceINR: 4199,
        priceUSD: 34,
        originalPriceUSD: 54,
        sku: 'NIHI-NCK-SLV-02',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        id: 'var-102-yellow-gold',
        name: 'Yellow Gold',
        colorHex: '#D4AF37',
        priceINR: 2899,
        originalPriceINR: 4499,
        priceUSD: 36,
        originalPriceUSD: 58,
        sku: 'NIHI-NCK-YG-02',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    priceBreakdown: {
      metalType: '18K Gold Plated 925 Silver (3.4g)',
      metalWeightGrams: 3.4,
      metalRatePerGramINR: 350,
      metalCostINR: 1190,
      gemstoneDescription: '42x Micro-Pavé Swiss Zircons',
      gemstoneCostINR: 760,
      makingChargesINR: 650,
      gstINR: 299,
      totalINR: 2899,
    },
    reviews: [
      {
        id: 'rev-201',
        author: 'Rhea Sen',
        rating: 5,
        date: '02 Feb 2026',
        title: 'Pure understated luxury',
        comment: 'So minimal and delicate! I customized the back with my anniversary date "12.04" and the engraving came out laser crisp.',
        verified: true,
        productVariant: 'Rose Gold',
      },
    ],
  },
  {
    id: 'nihi-103',
    name: 'Celestial Twilight Huggie Hoops',
    slug: 'celestial-twilight-huggie-hoops',
    subtitle: 'Chic snug-fit hoops studded with starburst baguette stones',
    category: 'Earrings',
    metal: '925 Sterling Silver',
    rating: 4.95,
    reviewCount: 412,
    badge: 'Bestseller',
    description: 'Designed for 24/7 effortless wear, these celestial huggies feature an ultra-secure click-latch closure that never snags on hair or clothing. Embellished with alternating baguette and round stones for an ethereal twinkle.',
    details: [
      'Secure hinge-click closure designed for sleeping and showering',
      'Solid 925 Silver with hypoallergenic post',
      'Outer diameter: 12mm, Inner diameter: 9mm',
      'Lightweight at just 1.9 grams per pair',
    ],
    dimensions: 'Outer Diameter: 12mm, Thickness: 2.2mm',
    weightGrams: 1.9,
    warranty: '6-Month Plating & Authenticity Warranty',
    hallmark: '925 Pure Silver Stamped',
    allowsEngraving: false,
    hasSizes: false,
    featuredImage: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=1000&auto=format&fit=crop',
    variants: [
      {
        id: 'var-103-silver',
        name: 'Silver',
        colorHex: '#D8D8D8',
        priceINR: 1899,
        originalPriceINR: 2999,
        priceUSD: 24,
        originalPriceUSD: 38,
        sku: 'NIHI-EAR-SLV-03',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        id: 'var-103-rose-gold',
        name: 'Rose Gold',
        colorHex: '#E9708A',
        priceINR: 2099,
        originalPriceINR: 3299,
        priceUSD: 27,
        originalPriceUSD: 42,
        sku: 'NIHI-EAR-RG-03',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        id: 'var-103-yellow-gold',
        name: 'Yellow Gold',
        colorHex: '#D4AF37',
        priceINR: 2099,
        originalPriceINR: 3299,
        priceUSD: 27,
        originalPriceUSD: 42,
        sku: 'NIHI-EAR-YG-03',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    priceBreakdown: {
      metalType: '925 Pure Silver (1.9g)',
      metalWeightGrams: 1.9,
      metalRatePerGramINR: 320,
      metalCostINR: 608,
      gemstoneDescription: 'Baguette & Round Swiss Crystals',
      gemstoneCostINR: 590,
      makingChargesINR: 520,
      gstINR: 181,
      totalINR: 1899,
    },
    reviews: [
      {
        id: 'rev-301',
        author: 'Kavita Menon',
        rating: 5,
        date: '20 Jan 2026',
        title: 'Never taking these off!',
        comment: 'So lightweight! I even sleep wearing them and my sensitive ears have zero irritation. The click lock is super sturdy.',
        verified: true,
        productVariant: 'Silver',
      },
    ],
  },
  {
    id: 'nihi-104',
    name: 'Serena Infinite Tennis Bracelet',
    slug: 'serena-infinite-tennis-bracelet',
    subtitle: 'Seamless continuous row of lab-grown diamonds with double safety clasp',
    category: 'Bracelets',
    metal: 'Lab-grown Diamonds',
    rating: 4.98,
    reviewCount: 186,
    badge: 'Editor\'s Pick',
    description: 'The definitive luxury staple. Each stone is individually seated in a 4-prong basket designed to maximize ambient refraction. Features an engineered double-catch box lock for supreme peace of mind.',
    details: [
      'Total Diamond Equivalent: 4.2 Carats',
      'IGI Certified Grade Lab-Grown Diamonds (Color: E-F, Clarity: VVS1)',
      'Double safety safety clasp mechanism',
      'Available in 6.5 inch and 7.5 inch lengths',
    ],
    dimensions: 'Width: 3mm, Lengths: 16.5cm or 19cm',
    weightGrams: 7.8,
    warranty: 'Lifetime Authenticity & 1-Year Free Re-plating',
    hallmark: 'BIS Hallmarked & 925 / 14K Certified',
    allowsEngraving: true,
    engravingMaxChars: 10,
    hasSizes: true,
    sizeType: 'bangle',
    availableSizes: ['Size 2.4 (Small - 6.5")', 'Size 2.6 (Medium - 7.0")', 'Size 2.8 (Large - 7.5")'],
    featuredImage: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=1000&auto=format&fit=crop',
    variants: [
      {
        id: 'var-104-silver',
        name: 'Silver',
        colorHex: '#D8D8D8',
        priceINR: 5999,
        originalPriceINR: 8999,
        priceUSD: 75,
        originalPriceUSD: 115,
        sku: 'NIHI-BRC-SLV-04',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        id: 'var-104-rose-gold',
        name: 'Rose Gold',
        colorHex: '#E9708A',
        priceINR: 6499,
        originalPriceINR: 9499,
        priceUSD: 82,
        originalPriceUSD: 120,
        sku: 'NIHI-BRC-RG-04',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    priceBreakdown: {
      metalType: 'Solid 925 Silver Base with Platinum Plating (7.8g)',
      metalWeightGrams: 7.8,
      metalRatePerGramINR: 320,
      metalCostINR: 2496,
      gemstoneDescription: '4.2 Ct Lab-Grown Diamonds (VVS / E-F)',
      gemstoneCostINR: 2150,
      makingChargesINR: 850,
      gstINR: 503,
      totalINR: 5999,
    },
    reviews: [
      {
        id: 'rev-401',
        author: 'Deepika Rao',
        rating: 5,
        date: '10 Feb 2026',
        title: 'Looks like a ₹2 Lakh diamond bracelet!',
        comment: 'The fire and scintillation is unbelievable. The double clasp is so secure. Best purchase of this year.',
        verified: true,
        productVariant: 'Silver / Size 2.4',
      },
    ],
  },
  {
    id: 'nihi-105',
    name: 'Ares Signet Band for Men',
    slug: 'ares-signet-band-for-men',
    subtitle: 'Brushed matte top surface with high-polish beveled edges',
    category: "Men's",
    metal: '925 Sterling Silver',
    rating: 4.88,
    reviewCount: 94,
    badge: 'New Arrival',
    description: 'Understated masculine sophistication. Crafted from hefty 925 sterling silver featuring a flat brushed top slate ready for monogram engraving, paired with mirror-polished beveled comfort rails.',
    details: [
      'Heavyweight 925 solid sterling silver',
      'Brushed satin top with scratch-resistant oxidation coat',
      'Laser engravable with initials, dates, or crests',
      'Ergonomic comfort-curved inner profile',
    ],
    dimensions: 'Slate surface: 12mm x 8mm, Shank width: 4mm',
    weightGrams: 6.2,
    warranty: '6-Month Anti-Tarnish Warranty',
    hallmark: 'BIS Hallmarked & 925 Stamped',
    allowsEngraving: true,
    engravingMaxChars: 6,
    hasSizes: true,
    sizeType: 'ring',
    availableSizes: ['US 8 (18.1mm)', 'US 9 (18.9mm)', 'US 10 (19.8mm)', 'US 11 (20.6mm)', 'US 12 (21.4mm)'],
    featuredImage: 'https://images.unsplash.com/photo-1534126511673-b6899657816a?q=80&w=1000&auto=format&fit=crop',
    variants: [
      {
        id: 'var-105-silver',
        name: 'Silver',
        colorHex: '#D8D8D8',
        priceINR: 3199,
        originalPriceINR: 4899,
        priceUSD: 40,
        originalPriceUSD: 62,
        sku: 'NIHI-MEN-SLV-05',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1534126511673-b6899657816a?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    priceBreakdown: {
      metalType: 'Solid 925 Sterling Silver (6.2g)',
      metalWeightGrams: 6.2,
      metalRatePerGramINR: 320,
      metalCostINR: 1984,
      gemstoneDescription: 'Nil (All Metal Finish)',
      gemstoneCostINR: 0,
      makingChargesINR: 890,
      gstINR: 325,
      totalINR: 3199,
    },
    reviews: [
      {
        id: 'rev-501',
        author: 'Arjun Nambiar',
        rating: 5,
        date: '05 Feb 2026',
        title: 'Perfect weight and premium feel',
        comment: 'Got my initials "AN" engraved on top. Looks sharp with both suits and casual outfits.',
        verified: true,
        productVariant: 'Silver / US 10',
      },
    ],
  },
  {
    id: 'nihi-106',
    name: 'Eternal Duo Royal Velvet Gift Hamper',
    slug: 'eternal-duo-royal-velvet-gift-hamper',
    subtitle: 'Includes Aethel Solitaire Necklace + Matching Earrings in Wax-Sealed Gift Box',
    category: 'Gifts',
    metal: '14K Rose Gold',
    rating: 4.97,
    reviewCount: 310,
    badge: 'Bestseller',
    description: 'The ultimate luxury gifting gesture. A coordinated jewelry set comprising our signature Solitaire Pendant and Studs nestled in an opulent emerald-green velvet box with a wax-sealed parchment card personalized with your custom message.',
    details: [
      'Complete matching set: 1x Solitaire Necklace + 1x Pair Stud Earrings',
      'Solid 925 Silver coated with 14K Rose Gold',
      'Handcrafted velvet jewelry showcase box with gold hot-stamped ribbon',
      'Complimentary handwritten calligraphy wax-sealed message card',
      'Nihi Studio Gift Bag & Polishing Cloth included',
    ],
    dimensions: 'Pendant: 1.0ct eq, Studs: 0.5ct eq each',
    weightGrams: 5.1,
    warranty: '6-Month Plating & Authenticity Warranty',
    hallmark: 'BIS Hallmarked & 925 Pure Silver Stamped',
    allowsEngraving: true,
    engravingMaxChars: 12,
    hasSizes: false,
    featuredImage: 'https://images.unsplash.com/photo-1513094735237-8f2714d57c13?q=80&w=1000&auto=format&fit=crop',
    variants: [
      {
        id: 'var-106-rose-gold',
        name: 'Rose Gold',
        colorHex: '#E9708A',
        priceINR: 4599,
        originalPriceINR: 6999,
        priceUSD: 58,
        originalPriceUSD: 88,
        sku: 'NIHI-GFT-RG-06',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1513094735237-8f2714d57c13?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        id: 'var-106-silver',
        name: 'Silver',
        colorHex: '#D8D8D8',
        priceINR: 4299,
        originalPriceINR: 6599,
        priceUSD: 54,
        originalPriceUSD: 82,
        sku: 'NIHI-GFT-SLV-06',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1513094735237-8f2714d57c13?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    priceBreakdown: {
      metalType: '14K Rose Gold Plated 925 Silver (5.1g)',
      metalWeightGrams: 5.1,
      metalRatePerGramINR: 350,
      metalCostINR: 1785,
      gemstoneDescription: 'Solitaire Pendant + Matching Stud Gems',
      gemstoneCostINR: 1250,
      makingChargesINR: 950,
      gstINR: 614,
      totalINR: 4599,
    },
    reviews: [
      {
        id: 'rev-601',
        author: 'Siddharth Roy',
        rating: 5,
        date: '12 Feb 2026',
        title: 'My fiancée was in tears of joy!',
        comment: 'The packaging is 10/10. The wax-sealed letter adds such a royal romantic touch. Will definitely buy again.',
        verified: true,
        productVariant: 'Rose Gold',
      },
    ],
  },
  {
    id: 'nihi-107',
    name: 'Aura Halo Emerald-Cut Ring',
    slug: 'aura-halo-emerald-cut-ring',
    subtitle: 'Vintage emerald-cut centerpiece framed by a radiant micro-pave halo',
    category: 'Rings',
    metal: '18K Gold Plated',
    rating: 4.92,
    reviewCount: 164,
    badge: 'Sale',
    description: 'An ode to vintage Art Deco glamour. The geometric emerald-cut center stone reflects long, clean stepped facets of light, surrounded by a pavé halo and a diamond-encrusted shank.',
    details: [
      'Emerald Cut 8x6mm AAA+ Cubic Zirconia',
      '18K Yellow Gold Plating over Hallmarked 925 Silver',
      'Prong-set halo and split band shank',
      'Protected with long-lasting ceramic e-coating',
    ],
    dimensions: 'Center stone: 8x6mm, Band width: 2.0mm',
    weightGrams: 3.1,
    warranty: '6-Month Anti-Tarnish Warranty',
    hallmark: '925 Hallmarked',
    allowsEngraving: true,
    engravingMaxChars: 10,
    hasSizes: true,
    sizeType: 'ring',
    availableSizes: ['US 5 (15.7mm)', 'US 6 (16.5mm)', 'US 7 (17.3mm)', 'US 8 (18.1mm)', 'US 9 (18.9mm)'],
    featuredImage: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=1000&auto=format&fit=crop',
    variants: [
      {
        id: 'var-107-yellow-gold',
        name: 'Yellow Gold',
        colorHex: '#D4AF37',
        priceINR: 2799,
        originalPriceINR: 4499,
        priceUSD: 35,
        originalPriceUSD: 56,
        sku: 'NIHI-RNG-YG-07',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        id: 'var-107-silver',
        name: 'Silver',
        colorHex: '#D8D8D8',
        priceINR: 2599,
        originalPriceINR: 4199,
        priceUSD: 33,
        originalPriceUSD: 53,
        sku: 'NIHI-RNG-SLV-07',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    priceBreakdown: {
      metalType: '18K Gold Plated 925 Silver (3.1g)',
      metalWeightGrams: 3.1,
      metalRatePerGramINR: 350,
      metalCostINR: 1085,
      gemstoneDescription: 'Emerald Cut Center + 32 Halo Stones',
      gemstoneCostINR: 890,
      makingChargesINR: 550,
      gstINR: 274,
      totalINR: 2799,
    },
    reviews: [
      {
        id: 'rev-701',
        author: 'Meera Kapoor',
        rating: 5,
        date: '18 Jan 2026',
        title: 'Regal and classy',
        comment: 'Emerald cut is so difficult to find with this grade of sparkle. Stunning in yellow gold!',
        verified: true,
        productVariant: 'Yellow Gold / US 6',
      },
    ],
  },
  {
    id: 'nihi-108',
    name: 'Vermeil Infinity Knot Bangle',
    slug: 'vermeil-infinity-knot-bangle',
    subtitle: 'Sculpted open-cuff bangle celebrating endless friendship and love',
    category: 'Bracelets',
    metal: '14K Rose Gold',
    rating: 4.89,
    reviewCount: 145,
    badge: 'Trending',
    description: 'An elegant statement of eternal connection. Handcrafted with a graceful twist knot centerpiece accented with pavé set crystals on a pliable cuff that effortlessly fits any wrist size.',
    details: [
      'Flexible cuff design with gentle flex adjustment',
      'Solid 925 Silver with 14K Rose Gold vermeil',
      'Pavé set micro zircons along one loop of the knot',
      'Stamped with 925 Hallmark guarantee',
    ],
    dimensions: 'Band thickness: 3mm, Cuff diameter: 60mm (adjustable)',
    weightGrams: 5.4,
    warranty: '6-Month Plating Warranty',
    hallmark: 'BIS Hallmarked 925',
    allowsEngraving: true,
    engravingMaxChars: 12,
    hasSizes: true,
    sizeType: 'bangle',
    availableSizes: ['Adjustable Small (2.2 - 2.4)', 'Adjustable Medium/Large (2.6 - 2.8)'],
    featuredImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop',
    variants: [
      {
        id: 'var-108-rose-gold',
        name: 'Rose Gold',
        colorHex: '#E9708A',
        priceINR: 3299,
        originalPriceINR: 5199,
        priceUSD: 42,
        originalPriceUSD: 65,
        sku: 'NIHI-BNG-RG-08',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=1000&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=1000&auto=format&fit=crop',
        ],
      },
      {
        id: 'var-108-silver',
        name: 'Silver',
        colorHex: '#D8D8D8',
        priceINR: 2999,
        originalPriceINR: 4799,
        priceUSD: 38,
        originalPriceUSD: 60,
        sku: 'NIHI-BNG-SLV-08',
        inStock: true,
        images: [
          'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=1000&auto=format&fit=crop',
        ],
      },
    ],
    priceBreakdown: {
      metalType: '14K Rose Gold Plated Silver (5.4g)',
      metalWeightGrams: 5.4,
      metalRatePerGramINR: 350,
      metalCostINR: 1890,
      gemstoneDescription: 'Pavé Micro Zircons (18 Stones)',
      gemstoneCostINR: 450,
      makingChargesINR: 650,
      gstINR: 309,
      totalINR: 3299,
    },
    reviews: [
      {
        id: 'rev-801',
        author: 'Natasha Wadhwa',
        rating: 5,
        date: '25 Jan 2026',
        title: 'So comfortable and easy to wear',
        comment: 'I stack this with my wristwatch. It gives such an effortless classy vibe.',
        verified: true,
        productVariant: 'Rose Gold',
      },
    ],
  },
];

export const TRUST_BADGES = [
  {
    icon: 'ShieldCheck',
    title: '925 Hallmarked Authenticity',
    description: 'Every piece carries the official BIS certification & purity stamp.',
  },
  {
    icon: 'Sparkles',
    title: '6-Month Plating Warranty',
    description: 'Complimentary replating & polish guarantee for complete peace of mind.',
  },
  {
    icon: 'RotateCcw',
    title: '30-Day Easy Returns',
    description: 'Hassle-free reverse pick-up and instant exchange or refund.',
  },
  {
    icon: 'Truck',
    title: 'Free Express Shipping',
    description: 'Dispatched in discreet tamper-evident luxury packaging within 24 hours.',
  },
];

export const TESTIMONIALS = [
  {
    id: 't1',
    author: 'Kriti Sanon',
    role: 'Verified Customer, Mumbai',
    rating: 5,
    quote: 'Nihi Studio is my new go-to for daily fine jewelry. The shine does not fade even with daily hand washing, and the packaging makes you feel like royalty!',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
    productPurchased: 'Aethel Solitaire Sparkle Ring',
  },
  {
    id: 't2',
    author: 'Sunil & Tanvi G.',
    role: 'Anniversary Gift, Bangalore',
    rating: 5,
    quote: 'Ordered the customized engraved necklace for my wife. The laser engraving was sharp and the handwritten wax sealed note was a magical touch.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
    productPurchased: 'Luminary Floating Heart Pendant',
  },
  {
    id: 't3',
    author: 'Dr. Shruti Nair',
    role: 'Verified Customer, New Delhi',
    rating: 5,
    quote: 'Being a doctor I wash my hands 30 times a day. Most silver turns black or gives me an allergic rash, but Nihi\'s pure rhodium plating has held up flawlessly.',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=300&auto=format&fit=crop',
    productPurchased: 'Celestial Twilight Huggie Hoops',
  },
];

export const INSTAGRAM_POSTS = [
  {
    id: 'ig-1',
    handle: '@nihistudio_official',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=600&auto=format&fit=crop',
    likes: '2.4K',
    caption: 'Stack your everyday sparkle ✨ Tap to shop the Aethel Solitaire.',
  },
  {
    id: 'ig-2',
    handle: '@nihistudio_official',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=600&auto=format&fit=crop',
    likes: '1.8K',
    caption: 'Personalized memories etched in pure 925 silver 🕊️',
  },
  {
    id: 'ig-3',
    handle: '@nihistudio_official',
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=600&auto=format&fit=crop',
    likes: '3.1K',
    caption: 'The huggies you\'ll never take off 🌟 Safe for sleeping & showering.',
  },
  {
    id: 'ig-4',
    handle: '@nihistudio_official',
    image: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=600&auto=format&fit=crop',
    likes: '4.2K',
    caption: 'Tennis bracelet luxury, without the markup 💎',
  },
];
